//MOVIES
export const SET_POPULAR_MOVIES = "SET_POPULAR_MOVIES";
export const SET_TOP_RATED_MOVIES = "SET_TOP_RATED_MOVIES";
export const SET_COMING_SOON_MOVIES = "SET_COMING_SOON_MOVIES";
export const SET_NOWPLAYING = "SET_NOWPLAYING";
export const INC_NOWPLAYING_INDEX = "INC_NOWPLAYING_INDEX";
export const DEC_NOWPLAYING_INDEX = "DEC_NOWPLAYING_INDEX";

//TV
export const SET_TOP_RATED_TV = "SET_TOP_RATED_TV";
export const SET_ON_AIR = "SET_ON_AIR";
export const SET_AIRING_TODAY = "SET_AIRING_TODAY";
export const SET_POPULAR_TV = "SET_POPULAR_TV";
